apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: quev6f81d-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/quev6f81d-java-springboot-gitops