apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quev6f81d-java-springboot
  janus-idp.io/tekton: quev6f81d-java-springboot
  backstage.io/kubernetes-id: quev6f81d-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quev6f81d-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
